site_name: pseudify.me
site_url: https://www.pseudify.me/docs/2.0/
repo_url: https://github.com/waldhacker/pseudify-page/
repo_name: GitHub
edit_uri: 'edit/main/src/documentation/docs/'
site_description: pseudify
site_author: waldhacker UG (haftungsbeschränkt)
copyright: waldhacker UG (haftungsbeschränkt)
site_dir: '../public/docs/2.0/'
theme:
    name: readthedocs
    locale: en
    #logo: '/assets/img/Logo.svg'
    current_version: 2.0
    navigation_depth: 6
markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - nl2br
    - pymdownx.details
    - pymdownx.superfences
plugins:
    - callouts
    - glightbox
    - search
nav:
    - 'Introduction':
        - 'Overview': 'index.md'
    - 'Setup':
        - 'Installation': 'setup/installation.md'
        - 'Configuration': 'setup/configuration.md'
    - 'Usage':
        - 'Analyse and pseudonymize the database': 'usage.md'
    - 'Miscellaneous':
        - 'What to pseudonymise?': 'whatToPseudonymize.md'
        - 'Development': 'development.md'
        - 'Versions': 'versions.md'
        - 'License': 'license.md'
        - 'About the project': 'about.md'
